name: Aplicação Django

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Instalar Dependências
        run: |
          pip install pipenv
          pipenv sync --dev
          